awk '/public override void OnLeftRoom/ {
  print "    public override void OnRoomPropertiesUpdate(ExitGames.Client.Photon.Hashtable propertiesThatChanged)"
  print "    {"
  print "        CheckRoomPropertiesForVideo(propertiesThatChanged);"
  print "    }"
  print ""
  print "    private string lastProcessedVideo = \"\";"
  print "    private float lastProcessedTime = 0f;"
  print ""
  print "    private void CheckRoomPropertiesForVideo(ExitGames.Client.Photon.Hashtable properties)"
  print "    {"
  print "        int slotIndex = 2; // Slot 2 = Player 3"
  print "        "
  print "        string newVideoUrl = null;"
  print "        float newTimestamp = 0f;"
  print ""
  print "        if (properties.ContainsKey(\"Video_\" + slotIndex))"
  print "        {"
  print "            newVideoUrl = (string)properties[\"Video_\" + slotIndex];"
  print "            newTimestamp = (float)properties[\"Time_\" + slotIndex];"
  print "        }"
  print "        else if (properties.ContainsKey(\"GlobalVideo\"))"
  print "        {"
  print "            newVideoUrl = (string)properties[\"GlobalVideo\"];"
  print "            newTimestamp = (float)properties[\"GlobalTimestamp\"];"
  print "        }"
  print ""
  print "        if (newVideoUrl != null && (newVideoUrl != lastProcessedVideo || newTimestamp > lastProcessedTime))"
  print "        {"
  print "            lastProcessedVideo = newVideoUrl;"
  print "            lastProcessedTime = newTimestamp;"
  print "            ReceiveSelectVideoCommand(slotIndex, newVideoUrl);"
  print "        }"
  print "    }"
  print ""
}
{ print }' Oculus_VR_Player/Assets/Scripts/UserStatusSend.cs > temp.cs && mv temp.cs Oculus_VR_Player/Assets/Scripts/UserStatusSend.cs
